# Generated by Django 3.0.6 on 2020-05-05 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('as a developer', 'as a developer'), ('as a designer', 'as a designer'), ('as a documentation team', 'as a documentation team')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ContributeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('as a developer', 'as a developer'), ('as a designer', 'as a designer'), ('as a documentation team', 'as a documentation team')], max_length=25)),
                ('contributors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributors.ContributorModel')),
            ],
        ),
    ]
