# Generated by Django 3.0.6 on 2020-05-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateContributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('as a developer', 'as a developer'), ('as a designer', 'as a designer'), ('as a documentation team', 'as a documentation team')], max_length=25)),
                ('resume', models.FileField(upload_to='resume')),
            ],
        ),
        migrations.DeleteModel(
            name='ContributeModel',
        ),
        migrations.DeleteModel(
            name='ContributorModel',
        ),
    ]
