# Generated by Django 3.0.6 on 2020-05-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0002_auto_20200505_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createcontributor',
            name='resume',
        ),
    ]
