# Generated by Django 3.0.6 on 2020-05-05 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0003_remove_createcontributor_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcontributor',
            name='resume',
            field=models.FileField(default=django.utils.timezone.now, upload_to='static'),
            preserve_default=False,
        ),
    ]
